In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
df = pd.read_csv("../../01_data/raw/dataset_raw.csv")
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

In [4]:
print("Before:", len(df))

df = df.drop_duplicates()

print("After:", len(df))

Before: 9800
After: 9800

In [6]:
cat_cols = df.select_dtypes(include=["object", "string"]).columns
for c in cat_cols:
    df[c] = df[c].fillna("Unknown")

In [7]:
if "Order Date" in df.columns:
    df["Order Date"] = pd.to_datetime(df["Order Date"], errors="coerce")

    df["Order Year"] = df["Order Date"].dt.year
    df["Order Month"] = df["Order Date"].dt.month_name()

print(df.head())

   Row ID        Order ID Order Date   Ship Date       Ship Mode Customer ID  \
0       1  CA-2017-152156 2017-08-11  11/11/2017    Second Class    CG-12520
1       2  CA-2017-152156 2017-08-11  11/11/2017    Second Class    CG-12520
2       3  CA-2017-138688 2017-12-06  16/06/2017    Second Class    DV-13045
3       4  US-2016-108966 2016-11-10  18/10/2016  Standard Class    SO-20335
4       5  US-2016-108966 2016-11-10  18/10/2016  Standard Class    SO-20335

     Customer Name    Segment        Country             City       State  \
0      Claire Gute   Consumer  United States        Henderson    Kentucky
1      Claire Gute   Consumer  United States        Henderson    Kentucky
2  Darrin Van Huff  Corporate  United States      Los Angeles  California
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale     Florida
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale     Florida

   Postal Code Region       Product ID         Category Sub-Category  \
0      42420.0  South  FUR-BO-10001798        Furniture    Bookcases
1      42420.0  South  FUR-CH-10000454        Furniture       Chairs
2      90036.0   West  OFF-LA-10000240  Office Supplies       Labels
3      33311.0  South  FUR-TA-10000577        Furniture       Tables
4      33311.0  South  OFF-ST-10000760  Office Supplies      Storage

                                        Product Name     Sales  Order Year  \
0                  Bush Somerset Collection Bookcase  261.9600      2017.0
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400      2017.0
2  Self-Adhesive Address Labels for Typewriters b...   14.6200      2017.0
3      Bretford CR4500 Series Slim Rectangular Table  957.5775      2016.0
4                     Eldon Fold 'N Roll Cart System   22.3680      2016.0

  Order Month
0      August
1      August
2    December
3    November
4    November

In [8]:
if "Sales" in df.columns:
    df["Sales Category"] = np.where(df["Sales"] >= 500, "High", "Low")

df[["Sales", "Sales Category"]].head()

      Sales Sales Category
0  261.9600            Low
1  731.9400           High
2   14.6200            Low
3  957.5775           High
4   22.3680            Low

In [9]:
if "Sales" in df.columns:
    df["Sales Range"] = pd.cut(
        df["Sales"],
        bins=[0, 100, 500, df["Sales"].max()],
        labels=["Low", "Medium", "High"]
    )

df[["Sales", "Sales Range"]].head()

      Sales Sales Range
0  261.9600      Medium
1  731.9400        High
2   14.6200         Low
3  957.5775        High
4   22.3680         Low

In [10]:
os.makedirs("../../01_data/processed", exist_ok=True)

df.to_csv("../../01_data/processed/dataforge_cleaned.csv", index=False)

print("Data exported successfully!")

Data exported successfully!

In [11]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Region,Product ID,Category,Sub-Category,Product Name,Sales,Order Year,Order Month,Sales Category,Sales Range
0,1,CA-2017-152156,2017-08-11,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2017.0,August,Low,Medium
1,2,CA-2017-152156,2017-08-11,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,2017.0,August,High,High
2,3,CA-2017-138688,2017-12-06,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2017.0,December,Low,Low
3,4,US-2016-108966,2016-11-10,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,2016.0,November,High,High
4,5,US-2016-108966,2016-11-10,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2016.0,November,Low,Low

In [12]:
import os

os.makedirs("../../01_data/processed", exist_ok=True)

df.to_csv("../../01_data/processed/dataforge_cleaned.csv", index=False)

print("Data exported successfully!")

Data exported successfully!